### ISSUE TITLE
Automatic Declaration for my other teams

### ISSUE THREAD

**Issue by profotoce59** [XPEHO/YAKI#600]
**Context**

As a teammate or a captain
I want to be able not to inform all my teams when I was already declaring  my journey in one team
In order to not repeat my declaration as "absent" for all my other teams

**Expected Behavior**

When I declare myself in one team, for all my other teams I want to be automatically displayed as "absent" 

**Acceptance Criteria**

My status was automatically set as "absent" if I was already declared in a team
My status doesn't change automatically if I set a status by myself
But i also want to be able to set my status in 2 different teams

Exemple :  
 
 Team 1 : Morning = Remote
                Afternoon = Absent

Team 2 : Morning = Absent
                Afternoon = Remote
Technical Analysis needed.

**Comment by LaurentMag** [comment]
status update, will not use Absent

Team 1 : Morning = Remote
Afternoon = occupied

Team 2 : Morning = occupied
Afternoon = Remote
Technical Analysis needed.

**Comment by LaurentMag** [comment]
Tech part : 

Mobile backend: retrive current user declaration, must in the API get all his other team and automaticaly update the status for him.

case : User Roger in team A, B, C
Roger create declaration for team A  full day

Option 1 : 
Only create a delaration for team A, but when team B,C captain will check declaration, the request will check:
 there is a declaration made for this day, but not for the current team, just set status to "occupied"

PRO : 
Less declarations created, so less data used in the DB

CON:
? Will the get request heavier than Option2 ?
For log, how to handle the fact that there isn't any declaration created for team B & C


Option 2:
In front end only create declaration for teamA, but in API get all user's teams, and create declaration for the others teams with the status occupied.

PRO:
Easier as post declaration request is made and will work
Will create declaration for others teams for the logs

CON:
? Will the get request heavier than Option1 ?
Bigger data usage because more declaration created

**Comment by LaurentMag** [comment]
This has changed with bastiUI desgin
